### ISSUE TITLE
All_Syntax example no longer runs

### ISSUE THREAD

**Issue by tallpeak** [CategoricalData/fql#116]
Syntax example no longer runs in 03/18/2018 release (it works in Feb release):

It times out after 30 seconds, and the console window (if run from a Windows batch file) says:

java.lang.RuntimeException: Not on SQL typeside
        at catdata.aql.Query.toSQLViews(Query.java:797)
        at catdata.aql.gui.AqlViewer.makeQueryPanel(AqlViewer.java:581)
        at catdata.aql.gui.AqlViewer.visit(AqlViewer.java:569)
...

Environ: Win10, Java 9.04

**Comment by wisnesky** [comment]
fixed
